user:
    resource: "@UserBundle/Controller/"
    type:     annotation
    prefix:   /

web:
    resource: "@WebBundle/Controller/"
    type:     annotation
    prefix:   /

admin:
    resource: "@AdminBundle/Controller/"
    type:     annotation
    prefix:   /admin

app:
    resource: '@AppBundle/Controller/'
    type:     annotation
    prefix:

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"